<template>
  <div class="grid mb-16 mt-8 gap-8 px-8">
    <p>
      Made by <NuxtLink
        to="https://tcastanie.dev"
        target="_blank"
        class="underline underline-offset-2"
      >
        tcastanie.dev
      </NuxtLink>
    </p>
    <ul class="list-disc list-inside">
      <p>Some images are from Unsplash:</p>
      <li>
        <NuxtLink
          to="https://unsplash.com/fr/@hubblespacetelescope"
          target="_blank"
          class="underline underline-offset-2"
        >@hubblespacetelescope</NuxtLink>
      </li>
      <li>
        <NuxtLink
          to="https://unsplash.com/fr/@mnelson"
          target="_blank"
          class="underline underline-offset-2"
        >@mnelson</NuxtLink>
      </li>
    </ul>
    <p>Planets pictures and texts are generated by AI</p>
  </div>
</template>
